### ISSUE TITLE
Audio drag timeline scale does not change   

### ISSUE THREAD

**Issue by taowenqiang** [katspaugh/wavesurfer-multitrack#12]
When I add multiple audio tracks and I set the startCue property for all of them is there any way to change their starting position to 0 by default, because this will allow for a truncated preview of the audio,thank you

**Comment by katspaugh** [comment]
Not sure I understand the question. The startPosition is 0 be default already, and you can set a different one in the track settings.

**Comment by taowenqiang** [comment]
When setting the startCue property of the track, how can the leftmost starting point not be 0 by default, in other words, the starting position of the black mask is from any starting point and not from the start of the audio to the startCue position you set

**Comment by taowenqiang** [comment]
When I went to change start:0 in startCueRegion, the position of the black mask changed, but there was no sound in the front

**Comment by katspaugh** [comment]
It sounds like you want to visually trim the waveform or even the audio itself?
It's not possible via options, but you can use [custom CSS](https://wavesurfer-js.org/examples/#styling.js) to change the color of the black mask to the color of the background, essentially making it invisible.

**Comment by taowenqiang** [comment]
Yes, I need Region to put this black mask in the middle of the waveform or anywhere, so that the audio inside the black mask is silent, so as to achieve the effect of truncated playback preview of any area of the audio

**Comment by katspaugh** [comment]
You can write this custom logic in your app.
`multitrack.wavesurfers` will give you wavesurfer instances for each track, you can register the Regions plugin on them, add your own regions, subscribe to their `region-in` and `region-out` and call `wavesurfer.setMuted(true)`  on region-in.
