### ISSUE TITLE
Timeline in Multitrack Doesn't Adjust with Zoom

### ISSUE THREAD

**Issue by zaptrem** [katspaugh/wavesurfer-multitrack#20]
## Bug description
Timeline does not adjust with zoom level

## Environment
 - Browser: Chrome

## Minimal code snippet
https://wavesurfer-js.org/examples/#multitrack.js

## Expected result
Timeline changes with zoom

## Obtained result

https://github.com/katspaugh/wavesurfer.js/assets/1612230/c9954717-7ff2-4725-baba-a95c37d52f01

**Comment by psavva** [comment]
Following as I need to implement the same.

**Comment by katspaugh** [comment]
I'll prioritize it. 👍

**Comment by katspaugh** [comment]
Fixed in 0.3.1 ✅ 
Thanks for reporting!

**Comment by yarikLev04** [comment]
Hi @zaptrem, I apologise for writing in this chat, but this is the only place where I can write, please tell me what I'm doing wrong that my timeline is rendered this way. I mean it ends when my first audio ends + I dont understand why i have 2 timelines

<img width="1186" alt="Снимок экрана 2023-12-13 в 10 09 29" src="https://github.com/katspaugh/wavesurfer-multitrack/assets/91241935/add1a7d9-1dec-4d06-b9ea-9942b2dfdb7d">

MultiTrack.create(
      [
        {
          id: 1,
          draggable: true,
          startPosition: 0,
          url: 'https://www.mfiles.co.uk/mp3-downloads/angels-we-have-heard-on-high.mp3',
          options: {
            height: 54,
            waveColor: 'rgba(255, 255, 255, 0.80)',
            progressColor: 'rgba(255, 255, 255, 0.80)',
            barWidth: 3,
            barGap: 2,
            barRadius: 1,
            barHeight: 1,
            plugins: [
              TimelinePlugin.create({
                height: 10,
                insertPosition: 'beforebegin',
                primaryLabelInterval: 10,
                formatTimeCallback: (seconds: number) => seconds + ' s',
                style: {
                  fontSize: '10px',
                  color: '#2D5B88'
                }
              })
            ]
          }
        },
        {
          id: 2,
          draggable: true,
          startPosition: 0,
          options: {
            height: 54,
            waveColor: 'rgba(255, 255, 255, 0.80)',
            progressColor: 'rgba(255, 255, 255, 0.80)',
            barWidth: 3,
            barGap: 2,
            barRadius: 1,
            barHeight: 1
          },
          url: 'https://www.mfiles.co.uk/mp3-downloads/shepherds-shake-off-your-drowsy-sleep.mp3'
        },
        {
          id: 3,
          draggable: true,
          startPosition: 0,
          options: {
            height: 54,
            waveColor: 'rgba(255, 255, 255, 0.80)',
            progressColor: 'rgba(255, 255, 255, 0.80)',
            barWidth: 3,
            barGap: 2,
            barRadius: 1,
            barHeight: 1
          },
          url: 'https://www.mfiles.co.uk/mp3-downloads/daisy-bell.mp3'
        }
      ],
      {
        container: stemsWaveForm.current!,
        minPxPerSec: 10,
        rightButtonDrag: false,
        cursorWidth: 2,
        cursorColor: '#008EF3',
        trackBackground: 'rgba(0, 0, 0, 0.10);',
        trackBorderColor: '#494949',
        dragBounds: true,
        envelopeOptions: {
          lineColor: 'rgba(255, 0, 0, 0.7)',
          lineWidth: '4',
          dragPointSize: window.innerWidth < 600 ? 20 : 10,
          dragPointFill: 'rgba(255, 255, 255, 0.8)',
          dragPointStroke: 'rgba(255, 255, 255, 0.3)'
        }
      }
    )

**Comment by katspaugh** [comment]
Multitrack has its own Timeline, you don't need to initialize it on individual tracks. If you do that, it's expected that it spans only the duration of that track.

If you have any other questions, please feel free to post in our forum:
https://github.com/katspaugh/wavesurfer.js/discussions/categories/q-a
