### ISSUE TITLE
Regions support for multi tracks

### ISSUE THREAD

**Issue by logesh2496** [katspaugh/wavesurfer-multitrack#23]
Hi,
I would like to create Regions in the multitrack with track id. Is it possible?

**Comment by katspaugh** [comment]
You have full access to each track's wavesurfer via `multitrack.wavesurfers`, so you can register any plugin on them.

P.S. We use issues only for bug reports. If you have questions, please feel free to ask in the wavesurfer [forum](https://github.com/katspaugh/wavesurfer.js/discussions) in the future.
