### ISSUE TITLE
Listen to wavesurfer events

### ISSUE THREAD

**Issue by fabiantorress** [katspaugh/wavesurfer-multitrack#26]
Hi, how can I listen to the events that are fired by wavesurfer? Like _timeupdate_, _play_ and _pause_? 

Thanks in advance

**Comment by katspaugh** [comment]
multitrack.wavesurfers is an array of wavesurfers for the loaded tracks.
P.S. please don’t use issues for support questions. There’s a forum in the main wavesurfer repo.
