### ISSUE TITLE
How to change the single track volume like setVolume methods of wavesurfer.js 

### ISSUE THREAD

**Issue by v1ada** [katspaugh/wavesurfer-multitrack#6]
I tried to change the `volume` property of the `audios ` and `tracks` of the Multitrack object，but the sound doesn't change.
I need to customize to set the volume, how can I do this.

**Comment by katspaugh** [comment]
You can set the volume in your track settings, e.g.:

```js
const tracks = [
   {
      id: 1,
      draggable: false,
      startPosition: 14, // start time relative to the entire multitrack
      url: '/examples/audio/librivox.mp3',
      fadeInEnd: 5,
      fadeOutStart: 250,
      volume: 1,
  }
]
```

It's currently not possible to dynamically set the volume because each wavesurfer has an Envelope plugin enabled. This plugin essentially hijacks the volume control and doesn't allow changing it via code. I've filed an issue here to fix this: https://github.com/katspaugh/wavesurfer.js/issues/2995

**Comment by katspaugh** [comment]
@v1ada you can now call `setVolume` like this:

```js
const volume = 0.5
multitrack.wavesurfers.forEach((wavesurfer) => wavesurfer.setVolume(volume))
```

Cheers!

**Comment by v1ada** [comment]
> @v1ada你现在可以`setVolume`这样调用：
> 
> ```js
> const volume = 0.5
> multitrack.wavesurfers.forEach((wavesurfer) => wavesurfer.setVolume(volume))
> ```
> 
> 干杯!

Thanks for the answer to my question!
In my use, I found that the `updatePosition` method always adjusts the volume to 1.
https://github.com/katspaugh/wavesurfer-multitrack/blob/0269575286ff2c8d0eee47fb5c97767d2b458db4/src/multitrack.ts#L331C100-L331C100
I had to change it to `const newVolume = newTime >= (track.startCue || 0) && newTime < (track.endCue || Infinity) ? audio.volume : 0`

**Comment by v1ada** [comment]
> @v1ada你现在可以`setVolume`这样调用：
> 
> ```js
> const volume = 0.5
> multitrack.wavesurfers.forEach((wavesurfer) => wavesurfer.setVolume(volume))
> ```
> 
> 干杯!

Thanks for the answer to my question!
In my use, I found that the `updatePosition` method always adjusts the volume to 1.

https://github.com/katspaugh/wavesurfer-multitrack/blob/0269575286ff2c8d0eee47fb5c97767d2b458db4/src/multitrack.ts#L331C7-L331C105

I had to change it to `const newVolume = newTime >= (track.startCue || 0) && newTime < (track.endCue || Infinity) ? audio.volume : 0`

**Comment by v1ada** [comment]
> @v1ada你现在可以`setVolume`这样调用：
> 
> ```js
> const volume = 0.5
> multitrack.wavesurfers.forEach((wavesurfer) => wavesurfer.setVolume(volume))
> ```
> 
> 干杯！

> @v1ada你现在可以`setVolume`这样调用：
> 
> ```js
> const volume = 0.5
> multitrack.wavesurfers.forEach((wavesurfer) => wavesurfer.setVolume(volume))
> ```
> 
> 干杯!

Thanks for the answer to my question, this can work!
In my use, I found that the `updatePosition` method always adjusts the volume to 1.

https://github.com/katspaugh/wavesurfer-multitrack/blob/0269575286ff2c8d0eee47fb5c97767d2b458db4/src/multitrack.ts#L331C7-L331C105

I had to change it to 
```js
const newVolume = newTime >= (track.startCue || 0) && newTime < (track.endCue || Infinity) ? audio.volume : 0
```

**Comment by katspaugh** [comment]
That's a good fix, please do make a PR.

**Comment by v1ada** [comment]
> That's a good fix, please do make a PR.
I make a new PR, please check it out.
